# Generated by Django 4.2.16 on 2024-11-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('federation', models.CharField(max_length=30)),
                ('certificate_name', models.CharField(max_length=50)),
                ('max_depth', models.IntegerField(blank=True)),
            ],
        ),
    ]
